group 'com.checkoutflow.checkout_flow_flutter'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.2.20'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'com.android.library'

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io'
            content { includeGroup 'com.github.checkout' }
        }
        maven {
            url 'https://maven.fpregistry.io/releases'
            content { includeGroup 'com.fingerprint.android' }
        }
    }
}

android {
    namespace 'com.checkoutflow.checkout_flow_flutter'
    compileSdk 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk 24
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    implementation 'com.checkout:checkout-android-components:2.6.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
}
